name: Generate RSS Feed

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        run: python update-feeds.py

      - name: Check for changes and commit
        run: |
          # Asegúrate de que todos los archivos XML generados sean agregados
          git add *.xml

          # Verificar si hay cambios y solo hacer commit si los hay
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
          else
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -m "Update RSS feed"
            git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git HEAD:main
          fi